notifications:
  email: false

language: cpp


cache:
  directories:
  - $HOME/.ccache

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - gdb
      - g++-4.9
      - gfortran-4.9
      - liblapack-dev
      - clang-3.8
      - csh
      - python3.5
      - libpython3.5-dev
      - sox
      - swig3.0

branches:
  only:
    - master

before_install:
  - cat /proc/sys/kernel/core_pattern
  - export XROOT=~/xroot
  - tools/extras/travis_install_bindeps.sh $XROOT
  - export PATH=$XROOT/usr/bin:$PATH
  - export SWIG=swig3.0

install:
  - sudo apt-get install python3.6
  - pip3 install -r idlak-server/requirements.txt

before_script:
  - which ccache
  - ccache --version
  - ccache --show-stats
  - ccache --zero-stats --max-size=3G

env:
  - CI_TARGETS="depend"       # Job1: Build main programs.
  - CI_TARGETS="all"          # Job2: Build main programs.
  - CI_TARGETS="ext_depend"   # Job3: Build extra programs
  - CI_TARGETS="online"       # Job4.a: Build extra programs
  - CI_TARGETS="onlinebin"    # Job4.b: Build extra programs
  - CI_TARGETS="pyIdlak"      # Job4.c: Build extra programs
  - CI_TARGETS="test"         # Job5: Test libraries.
  - CI_TARGETS="test_server"  # Job6: Test server.
  #### ext_test? adds 5min compile, runs 1 test.

script:
  # See http://petereisentraut.blogspot.com/2011/05/ccache-and-clang.html and
  # http://peter.eisentraut.org/blog/2014/12/01/ccache-and-clang-part-3/
  # for the explanation why extra switches needed for clang with ccache.
  - CXX="ccache clang++-3.8 -Qunused-arguments -fcolor-diagnostics -Wno-tautological-compare"
    CFLAGS="-march=native -fPIC"
    LDFLAGS="-llapack -Wl,-fuse-ld=gold"
    INCDIRS="$XROOT/usr/include"
    LIBDIRS="$XROOT/usr/lib"
      tools/extras/travis_script.sh
#   To troubleshoot cache, add to above: CI_TARGETS=util CCACHE_LOGFILE=~/ccache.log

before_cache:
  - ccache --show-stats

after_failure:
  - tools/extras/travis_show_failures.sh
